INSERT INTO `wktech`.`produtos` (`Descricao`, `PrecoVenda`) VALUES ('Nemesis BG', '1199.00');
INSERT INTO `wktech`.`produtos` (`Descricao`, `PrecoVenda`) VALUES ('Civilization a New Dawn BG', '399.00');
INSERT INTO `wktech`.`produtos` (`Descricao`, `PrecoVenda`) VALUES ('Takenoko BG', '299.00');
INSERT INTO `wktech`.`produtos` (`Descricao`, `PrecoVenda`) VALUES ('Maracaibo BG', '479.90');
INSERT INTO `wktech`.`produtos` (`Descricao`, `PrecoVenda`) VALUES ('El Dorado BG', '278.90');
INSERT INTO `wktech`.`produtos` (`Descricao`, `PrecoVenda`) VALUES ('Ishtar BG', '327.90');
INSERT INTO `wktech`.`produtos` (`Descricao`, `PrecoVenda`) VALUES ('The Few and Cursed BG', '439.90');
INSERT INTO `wktech`.`produtos` (`Descricao`, `PrecoVenda`) VALUES ('Dominat Species BG', '899.90');
INSERT INTO `wktech`.`produtos` (`Descricao`, `PrecoVenda`) VALUES ('Suburbia BG', '199.78');
INSERT INTO `wktech`.`produtos` (`Descricao`, `PrecoVenda`) VALUES ('Terra Mystica BG', '789.90');
INSERT INTO `wktech`.`produtos` (`Descricao`, `PrecoVenda`) VALUES ('On Mars BG', '1090.90');
INSERT INTO `wktech`.`produtos` (`Descricao`, `PrecoVenda`) VALUES ('The Oracle of Delphi BG', '499.80');
INSERT INTO `wktech`.`produtos` (`Descricao`, `PrecoVenda`) VALUES ('Tapestry BG', '499.90');
INSERT INTO `wktech`.`produtos` (`Descricao`, `PrecoVenda`) VALUES ('Chaparral BG', '189.9');
INSERT INTO `wktech`.`produtos` (`Descricao`, `PrecoVenda`) VALUES ('Bora Bora GB', '350.9');
INSERT INTO `wktech`.`produtos` (`Descricao`, `PrecoVenda`) VALUES ('Blacksmith Brothers BG', '179.9');
INSERT INTO `wktech`.`produtos` (`Descricao`, `PrecoVenda`) VALUES ('Wingspan', '429.9');
INSERT INTO `wktech`.`produtos` (`Descricao`, `PrecoVenda`) VALUES ('Vast - As Cavernas de Cristais BG', '300.90');
INSERT INTO `wktech`.`produtos` (`Descricao`, `PrecoVenda`) VALUES ('Lisboa BG', '789.9');
INSERT INTO `wktech`.`produtos` (`Descricao`, `PrecoVenda`) VALUES ('Dogs BG', '149.90');
INSERT INTO `wktech`.`produtos` (`Descricao`, `PrecoVenda`) VALUES ('Epic Zombies BG', '220.9');
